# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

select_rnd <- function(m, n) {
    .Call('_RegTree_select_rnd', PACKAGE = 'RegTree', m, n)
}

find_cut <- function(x, y, mu) {
    .Call('_RegTree_find_cut', PACKAGE = 'RegTree', x, y, mu)
}

best_split <- function(X, y, mu, n) {
    .Call('_RegTree_best_split', PACKAGE = 'RegTree', X, y, mu, n)
}

node_conditions <- function(Tree, j) {
    .Call('_RegTree_node_conditions', PACKAGE = 'RegTree', Tree, j)
}

RegTree <- function(y, X, max_nodes = 64L, threshold = 0.01) {
    .Call('_RegTree_RegTree', PACKAGE = 'RegTree', y, X, max_nodes, threshold)
}

FitVec <- function(x, Tree, maxit = 1000L) {
    .Call('_RegTree_FitVec', PACKAGE = 'RegTree', x, Tree, maxit)
}

FitMat <- function(X, Tree) {
    .Call('_RegTree_FitMat', PACKAGE = 'RegTree', X, Tree)
}

RegForest <- function(y, X, max_nodes = 64L, threshold = 0.01, draws = 500L) {
    .Call('_RegTree_RegForest', PACKAGE = 'RegTree', y, X, max_nodes, threshold, draws)
}

FitField <- function(X, Trees) {
    .Call('_RegTree_FitField', PACKAGE = 'RegTree', X, Trees)
}

