# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

select_rnd <- function(m, n) {
    .Call('_RegTree_select_rnd', PACKAGE = 'RegTree', m, n)
}

quickreg <- function(x, y, r) {
    .Call('_RegTree_quickreg', PACKAGE = 'RegTree', x, y, r)
}

find_cut <- function(x, y, ind) {
    .Call('_RegTree_find_cut', PACKAGE = 'RegTree', x, y, ind)
}

best_split <- function(X, y, ind, n) {
    .Call('_RegTree_best_split', PACKAGE = 'RegTree', X, y, ind, n)
}

testfun <- function(x) {
    .Call('_RegTree_testfun', PACKAGE = 'RegTree', x)
}

RegTree <- function(y, X, max_nodes = 31L) {
    .Call('_RegTree_RegTree', PACKAGE = 'RegTree', y, X, max_nodes)
}

FitVec <- function(x, Tree, maxit = 1000L) {
    .Call('_RegTree_FitVec', PACKAGE = 'RegTree', x, Tree, maxit)
}

FitMat <- function(X, Tree) {
    .Call('_RegTree_FitMat', PACKAGE = 'RegTree', X, Tree)
}

RegForest <- function(y, X, max_nodes = 31L, draws = 1000L) {
    .Call('_RegTree_RegForest', PACKAGE = 'RegTree', y, X, max_nodes, draws)
}

FitField <- function(X, Trees) {
    .Call('_RegTree_FitField', PACKAGE = 'RegTree', X, Trees)
}

find_scut <- function(x, y) {
    .Call('_RegTree_find_scut', PACKAGE = 'RegTree', x, y)
}

best_ssplit <- function(X, y, n) {
    .Call('_RegTree_best_ssplit', PACKAGE = 'RegTree', X, y, n)
}

node_conditions <- function(Tree, j) {
    .Call('_RegTree_node_conditions', PACKAGE = 'RegTree', Tree, j)
}

StdRegTree <- function(y, X, max_nodes = 64L, threshold = 0.01) {
    .Call('_RegTree_StdRegTree', PACKAGE = 'RegTree', y, X, max_nodes, threshold)
}

FitSVec <- function(x, Tree, maxit = 1000L) {
    .Call('_RegTree_FitSVec', PACKAGE = 'RegTree', x, Tree, maxit)
}

FitSMat <- function(X, Tree) {
    .Call('_RegTree_FitSMat', PACKAGE = 'RegTree', X, Tree)
}

RndForest <- function(y, X, max_nodes = 64L, threshold = 0.01, draws = 500L) {
    .Call('_RegTree_RndForest', PACKAGE = 'RegTree', y, X, max_nodes, threshold, draws)
}

StdFitField <- function(X, Trees) {
    .Call('_RegTree_StdFitField', PACKAGE = 'RegTree', X, Trees)
}

